#!/usr/bin/env python3
#
# EPITECH PROJECT, 2020
# 201yams_2019
# File description:
# 201yams
#

import sys
import math

def check_for_err():
    halp = open("help", "r")

    if len(sys.argv) > 1 and sys.argv[1] == "-h":
        print(halp.read(), end = '')
        sys.exit(0)
    if len(sys.argv) != 2:
        print("Flag error. Try -h for more informations.")
        sys.exit(84)

    try:
        flag = (float(sys.argv[1]))
    except ValueError:
        print("Flag error. Try -h for more informations.")
        sys.exit(84)
    return flag

def calc(val):
    print(val)
    return 0

def main():
    x = check_for_err()
    calc(x)

if __name__ == "__main__":
    main()
